### PR TITLE
Respect dual licensed dependencies.

### PR DESCRIPTION
**Pull request by ercpe**
If a dependency has more than one license, check that at least one of these licenses is in white list and none is in the blacklist.

### CODE REVIEW

**Comment by ercpe** [comment]
Any update on this one?

**Comment by tchemit** [comment]
Thanks for the patch :+1:

**Comment by ercpe** [comment]
Could you please publish 1.10 to maven central? Thanks!

**Comment by tchemit** [comment]
Done! enjoy and share :+1:

**Pull request closed without merging**
