### PR TITLE
Fixed "Configuration property 'trimHeaderLine' doesn't take any effect. #128"

### PR DESCRIPTION
**Pull request by xeagle2**
Fixed "Configuration property 'trimHeaderLine' doesn't take any effect. #128"

### CODE REVIEW

**Comment by tchemit** [comment]
thanks for patch :)

**Comment by xeagle2** [comment]
welcome :)

**Comment by xeagle2** [comment]
Would it be possible to make a new release with the latest bugfixes PR #130, PR #131 ?

**Comment by p-pandya** [comment]
Hello, We are also looking forward to this new release with the latest bug-fixes. Thanks in advance!

**Comment by ppalaga** [comment]
I hope I can release within a week.

**Pull request merged**
