### PR TITLE
Fix #324 Remove unnecessary manual dependency resolution

### LINKED ISSUE #324: AggregateAddThirdParty (and probably anything else using DependenciesTool) resolves unnecessary artifacts
On a project with the following dependencies:
```
        <!-- Depends on old hbase-annotations, which depends on jdk.tools -->
        <dependency>
            <groupId>org.apache.hive.hcatalog</groupId>
            <artifactId>hive-hcatalog-core</artifactId>
            <version>2.3.4</version>
        </dependency>
        <!-- This has a newer hbase-annotations without jdk.tools. This path to hbase-annotations is shorter, so has precedence -->
        <dependency>
            <groupId>org.apache.storm</groupId>
            <artifactId>child2</artifactId>
            <version>${project.version}</version>
        </dependency>
```
where child2 has the dependency
```
<dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-annotations</artifactId>
            <version>2.1.3</version>
        </dependency>
```

the expected behavior is that the license plugin should resolve only hbase-annotations 2.1.3, and thus not resolve jdk.tools. What actually happens is that both hbase-annotations 2.1.3 and 1.1.1 (incldued by hive-hcatalog-core) are resolved. This causes the build to fail on Java 9+.

I'll put up a PR with a test and fix shortly.

### PR DESCRIPTION
**Pull request by srdo**
Please see https://github.com/mojohaus/license-maven-plugin/issues/324

The fix here is to remove the manual dependency resolution in DependenciesTool. We already configure the mojos to require dependency resolution up to test scope, so all dependencies are already resolved and present in the injected MavenProject(s).

I realize that https://github.com/mojohaus/license-maven-plugin/issues/219 calls for programmatic dependency resolution, but I think that will be easier to implement once the plugin is upgraded to newer APIs. For now, the code in DependenciesTool is unnecessary and causes this bug.

I'll put up a PR for upgrading to Maven 3 APIs soon, which will depend on this PR.

### CODE REVIEW

**Comment by srdo** [comment]
One of the builds on Appveyor failed, but it's not the test I added, and it doesn't fail for me locally or on Travis. The log on Appveyor just refers to the integration test build log. Do you have access to that log @ppalaga? I don't seem to be able to find it.

**Comment by ppalaga** [comment]
> One of the builds on Appveyor failed, but it's not the test I added, and it doesn't fail for me locally or on Travis. 

Appveyor is Windows. Do you use Windows locally?

> The log on Appveyor just refers to the integration test build log. Do you have access to that log @ppalaga?

No, Appveyor, much like TravisCI has no notion of persistent workspace. The only way to debug this is to add `type path\to\the\log` to `on_failure` of `appveyor.yml`.

I pressed "rebuild" on the failed task, FWIW.

**Comment by srdo** [comment]
I use Windows, but through the Linux subsystem. It looks like the test passes now, maybe it is flaky on WIndows. I'll try running it a couple of times outside the Linux subsystem.

Regarding Appveyor, maybe we could store the target/it directory as artifacts on failure? https://help.appveyor.com/discussions/suggestions/828-store-some-artifacts-in-case-of-failure

**Comment by srdo** [comment]
Ran the tests 5 times locally on Windows with no failures. Maybe it was a network issue while downloading a license?

**Comment by ppalaga** [comment]
> Maybe it was a network issue while downloading a license?

Yeah, that's my theory. Let me review this PR.

> maybe we could store the target/it directory as artifacts on failure? https://help.appveyor.com/discussions/suggestions/828-store-some-artifacts-in-case-of-failure

A PR is welcome.

**Comment by ppalaga** [comment]
Does this commit have any potential to break the backwards compatibility?

**Comment by ppalaga** [comment]
Found no issue with WildFly Camel. This PR will be good to merge once you please reword to `Fix #324 Remove unnecessary manual dependency resolution`

**Comment by ppalaga** [comment]
My quick tests show this as a substantial perf gain a project as large as WildFly Camel. I am getting build time 2:08 using this PR vs. 3:15 using version 1.20.

**Comment by srdo** [comment]
Thanks for reviewing.

Reworded commit message.

I wouldn't expect backward compatibility to be broken. The deleted code wasn't doing anything useful, I think, and any difference to the dependencies resolved by Maven was probably incorrect.

I'll take a look at the appveyor thing soon.

**Comment by ppalaga** [comment]
Thanks @srdo !

**Pull request merged**
