### PR TITLE
Fixes #386 by removing all licenses - not just the first encountered.

### LINKED ISSUE #386: Override Unsuccessful On Dual-License Dependency
Adding an override for a dual license dependency fails to override all the licenses.
For example, if src/license/override-THIRD-PARTY.properties contains:
```
ch.qos.logback--logback-classic--1.2.3=Eclipse Public License (EPL) 1.0
```

The license report still lists both of the following licenses for logback-classic:
```
Eclipse Public License (EPL) 1.0
GNU Lesser General Public License
```

### PR DESCRIPTION
**Pull request by allan-shoup**

### CODE REVIEW

**Comment by tchemit** [comment]
@allan-shoup thanks for the patch

**Comment by tpage-alfresco** [comment]
I think the fix for this was accidentally reverted at the same time as #336.  Would it be possible to have a release containing this fix?  I'm currently in the process of setting up overrides for our project and it would be nice to remove our workaround for this issue.

**Comment by tchemit** [comment]
done.
Le lun. 17 mai 2021 à 17:09, Tom Page ***@***.***> a 
écrit :

**Comment by tchemit** [comment]
I will start a release if possible tomorrow :)

**Comment by tpage-alfresco** [comment]
Brilliant - thank you.

**Comment by tpage-alfresco** [comment]
I'm hitting the same issue again and I wondered if it would be possible for you to make a release containing this?

**Comment by tpage-alfresco** [comment]
For the time being I've made a release of 4736bf6 to our Nexus with the version 2.0.1.alfresco-1 - it's available here: https://nexus.alfresco.com/nexus/#nexus-search;gav~~~2.0.1.alfresco-1~~

We'd be happy to switch to the official 2.0.1 if you make a release.

**Pull request merged**
