### PR TITLE
Fix #117 Add possibility to include/exclude types

### LINKED ISSUE #117: Possibility to exclude/include certain artifact types
Our case are BOM dependencies which group dependencies together. These are there just for convenience, but are not important when it comes to the final assembly which includes all "relevant" licenses.
Currently it is not possible to filter for specific types, in our case to exclude BOMs, e.g.
```
         <execution>
            <id>exclude-bom</id>
            <goals>
              <goal>add-third-party</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <excludedTypes>pom</excludedTypes>
            </configuration>
          </execution>
```

I can provide a PR in the next days for that.

### PR DESCRIPTION
**Pull request by Matze2**
This PR allows to include/exclude artifact types in add-third-party and download-licenses.
My use case is to exclude "pom" dependencies that are not relevant for the final license compilation since they do not provide artifacts themselves.

### CODE REVIEW

**Comment by Matze2** [comment]
The travis configuration for "oraclejdk7" is wrong which makes the build fail.
The other platforms work correctly.

**Comment by tchemit** [comment]
ITs are down, I will check that is the problem.

**Comment by tchemit** [comment]
I found the problem (using junit 4.1 has a license which point to a 404 pb already solved AFAICR...

**Comment by tchemit** [comment]
So I can cleary merge this one ;)

**Comment by tchemit** [comment]
Thanks for the patch

**Pull request merged**
