### PR TITLE
Fix #271 aggregate-add-third-party evaluate acceptPomPackage also for current project

### LINKED ISSUE #271: acceptPomPackage does not have effect on the parent project when aggregate-add-third-party
Hi, we have a maven project (packaging pom) that aggregate only artifacts to be delivered to a client.
To do this usually we define dependencies on a project of with pom packaging and run the assembly plugin (or depedency-copy-dependency) to gathers all of them.
Now our department would realize a report to double check all licenses to give to a client.
The acceptPomPackage documents "To execute or not this mojo if project packaging is pom." but it is not executed if the project is that where we run the mvn command.

Looking the code the aggregate-add-third-party cycles on each project in the reactor but skip itself. This mean that only child module of kind pom are considered. From the documentation I expect it run a forked add-third-party also on the parent pom (the project from which I run mvn command).

### PR DESCRIPTION
**Pull request by nfalco79**
The aggregate-add-third-party goal now evaluate acceptPomPackage also for the current project like add-third-party does.

### CODE REVIEW

**Comment by nfalco79** [comment]
Yes I will do thos night

**Comment by ppalaga** [comment]
> Yes I will do thos night

I am doing it now.

**Comment by ppalaga** [comment]
Replaced by https://github.com/mojohaus/license-maven-plugin/pull/287

**Comment by nfalco79** [comment]
I do not see the 1.18 release on maven central. Is it correct? Usually within 24 hours the release is available by oss.sonatype.org

**Comment by ppalaga** [comment]
Voting is in progress https://groups.google.com/d/msg/mojohaus-dev/1AuEwCubmrg/RAajxHR2AQAJ

**Pull request closed without merging**
