### PR TITLE
Extended 'includedLicenses' and 'excludedLicenses' to use URL paramet…

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
Extended 'includedLicenses' and 'excludedLicenses' to use URL parameter for loading license list

### CODE REVIEW

**Comment by tchemit** [comment]
@Captain-P-Goldfish , you PR seems to breaks 2 its, do you know why ?

**Comment by v1v** [comment]
That's related to something else, as far as I see:
- https://github.com/mojohaus/license-maven-plugin/issues/121

**Comment by Captain-P-Goldfish** [comment]
on my locale machine 3 its were broken because a file is missing. But these tests failed even before I made a change. Also I corrected 2 JUnit tests since they failed on windows machine.

**Comment by tchemit** [comment]
thanks for the PR

**Pull request merged**
